[project]
name = "week-6-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Noel Vero", email = "jannoel.vero@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
]

[project.scripts]
week-6-project = "week_6_project:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
